package com.mp3t.utils;
import java.util.HashMap;
import java.util.Iterator;

public class Constants {

    public static final HashMap<Integer, String> genreIdToString = new HashMap<Integer, String>();
    public static final HashMap<String, Integer> genreStringToId = new HashMap<String, Integer>();
	
	static {
        genreIdToString.put(new Integer(0), "Blues");
        genreIdToString.put(new Integer(1), "Classic Rock");
        genreIdToString.put(new Integer(2), "Country");
        genreIdToString.put(new Integer(3), "Dance");
        genreIdToString.put(new Integer(4), "Disco");
        genreIdToString.put(new Integer(5), "Funk");
        genreIdToString.put(new Integer(6), "Grunge");
        genreIdToString.put(new Integer(7), "Hip-Hop");
        genreIdToString.put(new Integer(8), "Jazz");
        genreIdToString.put(new Integer(9), "Metal");
        genreIdToString.put(new Integer(10), "New Age");
        genreIdToString.put(new Integer(11), "Oldies");
        genreIdToString.put(new Integer(12), "Other");
        genreIdToString.put(new Integer(13), "Pop");
        genreIdToString.put(new Integer(14), "R&B");
        genreIdToString.put(new Integer(15), "Rap");
        genreIdToString.put(new Integer(16), "Reggae");
        genreIdToString.put(new Integer(17), "Rock");
        genreIdToString.put(new Integer(18), "Techno");
        genreIdToString.put(new Integer(19), "Industrial");
        genreIdToString.put(new Integer(20), "Alternative");
        genreIdToString.put(new Integer(21), "Ska");
        genreIdToString.put(new Integer(22), "Death Metal");
        genreIdToString.put(new Integer(23), "Pranks");
        genreIdToString.put(new Integer(24), "Soundtrack");
        genreIdToString.put(new Integer(25), "Euro-Techno");
        genreIdToString.put(new Integer(26), "Ambient");
        genreIdToString.put(new Integer(27), "Trip-Hop");
        genreIdToString.put(new Integer(28), "Vocal");
        genreIdToString.put(new Integer(29), "Jazz+Funk");
        genreIdToString.put(new Integer(30), "Fusion");
        genreIdToString.put(new Integer(31), "Trance");
        genreIdToString.put(new Integer(32), "Classical");
        genreIdToString.put(new Integer(33), "Instrumental");
        genreIdToString.put(new Integer(34), "Acid");
        genreIdToString.put(new Integer(35), "House");
        genreIdToString.put(new Integer(36), "Game");
        genreIdToString.put(new Integer(37), "Sound Clip");
        genreIdToString.put(new Integer(38), "Gospel");
        genreIdToString.put(new Integer(39), "Noise");
        genreIdToString.put(new Integer(40), "AlternRock");
        genreIdToString.put(new Integer(41), "Bass");
        genreIdToString.put(new Integer(42), "Soul");
        genreIdToString.put(new Integer(43), "Punk");
        genreIdToString.put(new Integer(44), "Space");
        genreIdToString.put(new Integer(45), "Meditative");
        genreIdToString.put(new Integer(46), "Instrumental Pop");
        genreIdToString.put(new Integer(47), "Instrumental Rock");
        genreIdToString.put(new Integer(48), "Ethnic");
        genreIdToString.put(new Integer(49), "Gothic");
        genreIdToString.put(new Integer(50), "Darkwave");
        genreIdToString.put(new Integer(51), "Techno-Industrial");
        genreIdToString.put(new Integer(52), "Electronic");
        genreIdToString.put(new Integer(53), "Pop-Folk");
        genreIdToString.put(new Integer(54), "Eurodance");
        genreIdToString.put(new Integer(55), "Dream");
        genreIdToString.put(new Integer(56), "Southern Rock");
        genreIdToString.put(new Integer(57), "Comedy");
        genreIdToString.put(new Integer(58), "Cult");
        genreIdToString.put(new Integer(59), "Gangsta");
        genreIdToString.put(new Integer(60), "Top 40");
        genreIdToString.put(new Integer(61), "Christian Rap");
        genreIdToString.put(new Integer(62), "Pop/Funk");
        genreIdToString.put(new Integer(63), "Jungle");
        genreIdToString.put(new Integer(64), "Native American");
        genreIdToString.put(new Integer(65), "Cabaret");
        genreIdToString.put(new Integer(66), "New Wave");
        genreIdToString.put(new Integer(67), "Psychadelic");
        genreIdToString.put(new Integer(68), "Rave");
        genreIdToString.put(new Integer(69), "Showtunes");
        genreIdToString.put(new Integer(70), "Trailer");
        genreIdToString.put(new Integer(71), "Lo-Fi");
        genreIdToString.put(new Integer(72), "Tribal");
        genreIdToString.put(new Integer(73), "Acid Punk");
        genreIdToString.put(new Integer(74), "Acid Jazz");
        genreIdToString.put(new Integer(75), "Polka");
        genreIdToString.put(new Integer(76), "Retro");
        genreIdToString.put(new Integer(77), "Musical");
        genreIdToString.put(new Integer(78), "Rock & Roll");
        genreIdToString.put(new Integer(79), "Hard Rock");
        genreIdToString.put(new Integer(80), "Folk");
        genreIdToString.put(new Integer(81), "Folk-Rock");
        genreIdToString.put(new Integer(82), "National Folk");
        genreIdToString.put(new Integer(83), "Swing");
        genreIdToString.put(new Integer(84), "Fast Fusion");
        genreIdToString.put(new Integer(85), "Bebob");
        genreIdToString.put(new Integer(86), "Latin");
        genreIdToString.put(new Integer(87), "Revival");
        genreIdToString.put(new Integer(88), "Celtic");
        genreIdToString.put(new Integer(89), "Bluegrass");
        genreIdToString.put(new Integer(90), "Avantgarde");
        genreIdToString.put(new Integer(91), "Gothic Rock");
        genreIdToString.put(new Integer(92), "Progressive Rock");
        genreIdToString.put(new Integer(93), "Psychedelic Rock");
        genreIdToString.put(new Integer(94), "Symphonic Rock");
        genreIdToString.put(new Integer(95), "Slow Rock");
        genreIdToString.put(new Integer(96), "Big Band");
        genreIdToString.put(new Integer(97), "Chorus");
        genreIdToString.put(new Integer(98), "Easy Listening");
        genreIdToString.put(new Integer(99), "Acoustic");
        genreIdToString.put(new Integer(100), "Humour");
        genreIdToString.put(new Integer(101), "Speech");
        genreIdToString.put(new Integer(102), "Chanson");
        genreIdToString.put(new Integer(103), "Opera");
        genreIdToString.put(new Integer(104), "Chamber Music");
        genreIdToString.put(new Integer(105), "Sonata");
        genreIdToString.put(new Integer(106), "Symphony");
        genreIdToString.put(new Integer(107), "Booty Bass");
        genreIdToString.put(new Integer(108), "Primus");
        genreIdToString.put(new Integer(109), "Porn Groove");
        genreIdToString.put(new Integer(110), "Satire");
        genreIdToString.put(new Integer(111), "Slow Jam");
        genreIdToString.put(new Integer(112), "Club");
        genreIdToString.put(new Integer(113), "Tango");
        genreIdToString.put(new Integer(114), "Samba");
        genreIdToString.put(new Integer(115), "Folklore");
        genreIdToString.put(new Integer(116), "Ballad");
        genreIdToString.put(new Integer(117), "Power Ballad");
        genreIdToString.put(new Integer(118), "Rhythmic Soul");
        genreIdToString.put(new Integer(119), "Freestyle");
        genreIdToString.put(new Integer(120), "Duet");
        genreIdToString.put(new Integer(121), "Punk Rock");
        genreIdToString.put(new Integer(122), "Drum Solo");
        genreIdToString.put(new Integer(123), "Acapella");
        genreIdToString.put(new Integer(124), "Euro-House");
        genreIdToString.put(new Integer(125), "Dance Hall");

        // ID's are typed as Integer because the combo box expects it
        Integer lkey;
        String value;
        Iterator<Integer> iterator = genreIdToString.keySet().iterator();
        while (iterator.hasNext()) {
            lkey = iterator.next();
            value = genreIdToString.get(lkey);
            genreStringToId.put(value, lkey);
        }
	}
}
